import {
  CHROMA_FACTOR,
  GRAY_CHROMA,
  LIGHTNESS,
  RADIUS,
  SCALES,
  SCALE_DEFS,
  SEMANTIC,
  CONTRAST_RULES,
  SPACING_STEPS,
  TYPE_SCALE,
} from './config.mjs';
import { contrast, hexToComponents, oklchToHex } from './color.mjs';

const THEMES = ['light', 'dark'];

/** @returns {{ light: Record<string, {step:number, hex:string, oklch:string}[]>, dark: … }} */
export function buildPalette() {
  const out = { light: {}, dark: {} };
  for (const theme of THEMES) {
    for (const name of SCALES) {
      const def = SCALE_DEFS[name];
      const hover = def.hoverDelta ?? 0.045;
      out[theme][name] = Array.from({ length: 12 }, (_, i) => {
        let L = LIGHTNESS[theme][i];
        if (i === 8) L = def.solid[theme];
        if (i === 9) L = theme === 'light' ? def.solid.light - hover : def.solid.dark + hover;
        if (def.lightText && theme === 'light' && i >= 10) L = def.lightText[i - 10];
        const C = def.neutral ? GRAY_CHROMA[theme][i] : def.chroma * CHROMA_FACTOR[theme][i];
        const { hex, C: fitted } = oklchToHex(L, C, def.hue);
        return {
          step: i + 1,
          hex,
          oklch: `oklch(${L.toFixed(3)} ${fitted.toFixed(3)} ${def.hue})`,
        };
      });
    }
  }
  return out;
}

export function resolve(palette, theme, ref) {
  if (ref.startsWith('#')) return ref;
  const [scale, step] = ref.split('.');
  return palette[theme][scale][Number(step) - 1].hex;
}

export function checkContrast(palette) {
  const results = [];
  for (const theme of THEMES) {
    const t = theme === 'light' ? 0 : 1;
    for (const [fg, bg, min] of CONTRAST_RULES) {
      const ratio = contrast(
        resolve(palette, theme, SEMANTIC[fg][t]),
        resolve(palette, theme, SEMANTIC[bg][t]),
      );
      results.push({
        theme,
        fg,
        bg,
        min,
        ratio: Math.round(ratio * 100) / 100,
        pass: ratio >= min,
      });
    }
  }
  return results;
}

const HEADER = '/* Generated by packages/tokens/scripts/build.mjs — do not edit by hand. */\n';
const cssRef = (ref) => (ref === '#ffffff' ? 'oklch(1 0 0)' : `var(--${ref.replace('.', '-')})`);

export function buildCss(palette) {
  const lines = [HEADER, '@custom-variant dark (&:where(.dark, .dark *));', ''];
  for (const theme of THEMES) {
    const t = theme === 'light' ? 0 : 1;
    lines.push(theme === 'light' ? ':root {' : '.dark {', `  color-scheme: ${theme};`);
    for (const name of SCALES)
      for (const s of palette[theme][name])
        lines.push(`  --${name}-${s.step}: ${s.oklch}; /* ${s.hex} */`);
    lines.push('');
    for (const [k, refs] of Object.entries(SEMANTIC)) lines.push(`  --${k}: ${cssRef(refs[t])};`);
    if (theme === 'light') lines.push('  --radius: 0.5rem;', '  --shadow-color: 222 20% 12%;');
    else lines.push('  --shadow-color: 0 0% 0%;');
    lines.push('}', '');
  }
  lines.push('@theme inline {');
  for (const name of SCALES)
    for (let i = 1; i <= 12; i++) lines.push(`  --color-${name}-${i}: var(--${name}-${i});`);
  for (const k of Object.keys(SEMANTIC)) lines.push(`  --color-${k}: var(--${k});`);
  lines.push(
    '',
    '  --font-sans: var(--font-geist-sans, "Geist"), ui-sans-serif, system-ui, sans-serif;',
    '  --font-mono: var(--font-geist-mono, "Geist Mono"), ui-monospace, "SFMono-Regular", monospace;',
    '',
    '  --radius-sm: calc(var(--radius) - 4px);',
    '  --radius-md: calc(var(--radius) - 2px);',
    '  --radius-lg: var(--radius);',
    '  --radius-xl: calc(var(--radius) + 4px);',
    '',
    '  --shadow-xs: 0 1px 2px 0 hsl(var(--shadow-color) / 0.05);',
    '  --shadow-sm: 0 1px 2px 0 hsl(var(--shadow-color) / 0.06), 0 1px 3px 0 hsl(var(--shadow-color) / 0.08);',
    '  --shadow-md: 0 4px 12px -2px hsl(var(--shadow-color) / 0.1), 0 2px 4px -2px hsl(var(--shadow-color) / 0.06);',
    '  --shadow-lg: 0 16px 40px -8px hsl(var(--shadow-color) / 0.18), 0 4px 12px -4px hsl(var(--shadow-color) / 0.08);',
    '',
    '  --ease-standard: cubic-bezier(0.2, 0, 0, 1);',
    '  --ease-out: cubic-bezier(0.16, 1, 0.3, 1);',
    '}',
    '',
    '@theme {',
    '  /* UI-dense type scale. App default text is text-base = 14px. */',
  );
  for (const [n, size, lh, ls] of TYPE_SCALE) {
    let l = `  --text-${n}: ${size / 16}rem; --text-${n}--line-height: ${lh / 16}rem;`;
    if (ls) l += ` --text-${n}--letter-spacing: ${ls}em;`;
    lines.push(l);
  }
  lines.push(
    '}',
    '',
    '@layer base {',
    '  *, ::before, ::after { border-color: var(--border); }',
    '  body { background: var(--background); color: var(--foreground); font-family: var(--font-sans); font-size: var(--text-base); line-height: var(--text-base--line-height); -webkit-font-smoothing: antialiased; }',
    '  :focus-visible { outline: 2px solid var(--ring); outline-offset: 2px; }',
    '}',
    '',
  );
  return lines.join('\n');
}

/** W3C DTCG: one object per theme for colors, plus dimensions and typography. */
export function buildDtcg(palette) {
  const color = (hex) => ({ $type: 'color', $value: hex });
  const out = { $description: 'Sanjou UI tokens (W3C DTCG). Generated — do not edit.' };
  for (const theme of THEMES) {
    const t = theme === 'light' ? 0 : 1;
    out[theme] = {
      scale: Object.fromEntries(
        SCALES.map((s) => [
          s,
          Object.fromEntries(palette[theme][s].map((x) => [String(x.step), color(x.hex)])),
        ]),
      ),
      ...Object.fromEntries(
        Object.entries(SEMANTIC).map(([k, r]) => [
          k,
          r[t].startsWith('#')
            ? color(r[t])
            : { $type: 'color', $value: `{${theme}.scale.${r[t]}}` },
        ]),
      ),
    };
  }
  out.radius = Object.fromEntries(
    Object.entries(RADIUS).map(([k, v]) => [
      k,
      { $type: 'dimension', $value: { value: v, unit: 'px' } },
    ]),
  );
  out.space = Object.fromEntries(
    SPACING_STEPS.map((k) => [
      String(k).replace('.', '_'),
      { $type: 'dimension', $value: { value: k * 4, unit: 'px' } },
    ]),
  );
  out.text = Object.fromEntries(
    TYPE_SCALE.map(([n, size, lh, ls]) => [
      n,
      {
        $type: 'typography',
        $value: {
          fontFamily: 'Geist',
          fontSize: { value: size, unit: 'px' },
          lineHeight: lh / size,
          letterSpacing: { value: ls, unit: 'em' },
        },
      },
    ]),
  );
  return out;
}

const figmaScopes = (k) => {
  if (['border', 'input', 'ring'].includes(k)) return ['STROKE_COLOR', 'EFFECT_COLOR'];
  if (k === 'foreground' || k.endsWith('-foreground') || k.endsWith('-text'))
    return ['TEXT_FILL', 'SHAPE_FILL', 'STROKE_COLOR'];
  return ['FRAME_FILL', 'SHAPE_FILL'];
};

/** Figma variables, one file per collection mode. `native` = Figma's own export shape; `hex` = plain strings for plugins. */
export function buildFigma(palette, format) {
  const val = (hex) =>
    format === 'native'
      ? { colorSpace: 'srgb', components: hexToComponents(hex), alpha: 1, hex: hex.toUpperCase() }
      : hex;
  const files = {};
  for (const theme of THEMES) {
    const t = theme === 'light' ? 0 : 1;
    const doc = { scale: {} };
    for (const s of SCALES)
      doc.scale[s] = Object.fromEntries(
        palette[theme][s].map((x) => [
          String(x.step),
          {
            $type: 'color',
            $value: val(x.hex),
            $extensions: { 'com.figma.scopes': ['ALL_SCOPES'] },
          },
        ]),
      );
    for (const [k, r] of Object.entries(SEMANTIC))
      doc[k] = {
        $type: 'color',
        $value: r[t].startsWith('#') ? val(r[t]) : `{scale.${r[t]}}`,
        $extensions: { 'com.figma.scopes': figmaScopes(k) },
      };
    files[`Color.${theme === 'light' ? 'Light' : 'Dark'}.tokens.json`] = doc;
  }
  files['Dimension.Value.tokens.json'] = {
    space: Object.fromEntries(
      SPACING_STEPS.map((k) => [
        String(k).replace('.', '_'),
        {
          $type: 'number',
          $value: k * 4,
          $extensions: { 'com.figma.scopes': ['GAP', 'WIDTH_HEIGHT'] },
        },
      ]),
    ),
    radius: Object.fromEntries(
      Object.entries(RADIUS).map(([k, v]) => [
        k,
        { $type: 'number', $value: v, $extensions: { 'com.figma.scopes': ['CORNER_RADIUS'] } },
      ]),
    ),
  };
  return files;
}

// Sanjou mark: an arc in ink and a triangle in indigo (48×48 grid).
const MARK_ARC = 'M5 43 A31 31 0 0 1 36 12 A27 27 0 0 0 16 43 Z';
const MARK_TRIANGLE = 'M28 43 L36 30 L44 43 Z';

/** Ink + accent of the mark per theme. Dark uses brand-text: indigo-9 is too dim on a dark page. */
export function logoColors(palette, theme) {
  const t = theme === 'light' ? 0 : 1;
  const accent = theme === 'light' ? SEMANTIC.brand : SEMANTIC['brand-text'];
  return {
    ink: resolve(palette, theme, SEMANTIC.foreground[t]),
    accent: resolve(palette, theme, accent[t]),
  };
}

/** Static mark for one theme (README, docs). */
export function buildLogo(palette, theme) {
  const { ink, accent } = logoColors(palette, theme);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">
  <path d="${MARK_ARC}" fill="${ink}"/>
  <path d="${MARK_TRIANGLE}" fill="${accent}"/>
</svg>
`;
}

/** Favicon that follows the browser color scheme. */
export function buildFavicon(palette) {
  const light = logoColors(palette, 'light');
  const dark = logoColors(palette, 'dark');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">
  <style>
    .ink { fill: ${light.ink}; }
    .accent { fill: ${light.accent}; }
    @media (prefers-color-scheme: dark) {
      .ink { fill: ${dark.ink}; }
      .accent { fill: ${dark.accent}; }
    }
  </style>
  <path class="ink" d="${MARK_ARC}"/>
  <path class="accent" d="${MARK_TRIANGLE}"/>
</svg>
`;
}

/** shadcn registry item that installs the theme into a consumer's globals.css. */
export function buildRegistryTheme(palette) {
  const vars = (theme) => {
    const t = theme === 'light' ? 0 : 1;
    const o = {};
    for (const s of SCALES) for (const x of palette[theme][s]) o[`${s}-${x.step}`] = x.oklch;
    for (const [k, r] of Object.entries(SEMANTIC)) o[k] = cssRef(r[t]);
    if (theme === 'light') o.radius = '0.5rem';
    return o;
  };
  const theme = {
    'font-sans': 'var(--font-geist-sans, "Geist"), ui-sans-serif, system-ui, sans-serif',
    'font-mono': 'var(--font-geist-mono, "Geist Mono"), ui-monospace, monospace',
    'radius-sm': 'calc(var(--radius) - 4px)',
    'radius-md': 'calc(var(--radius) - 2px)',
    'radius-lg': 'var(--radius)',
    'radius-xl': 'calc(var(--radius) + 4px)',
  };
  for (const s of SCALES)
    for (let i = 1; i <= 12; i++) theme[`color-${s}-${i}`] = `var(--${s}-${i})`;
  for (const k of Object.keys(SEMANTIC)) theme[`color-${k}`] = `var(--${k})`;
  for (const [n, size, lh, ls] of TYPE_SCALE) {
    theme[`text-${n}`] = `${size / 16}rem`;
    theme[`text-${n}--line-height`] = `${lh / 16}rem`;
    if (ls) theme[`text-${n}--letter-spacing`] = `${ls}em`;
  }
  return {
    name: 'theme',
    type: 'registry:theme',
    title: 'Sanjou theme',
    description:
      'Sanjou UI color scales, semantic tokens, radius and type scale (light + dark). Generated from packages/tokens.',
    cssVars: { theme, light: vars('light'), dark: vars('dark') },
  };
}

export function buildContrastReport(results) {
  const rows = results.map(
    (r) =>
      `| ${r.theme} | \`${r.fg}\` on \`${r.bg}\` | ${r.ratio.toFixed(2)}:1 | ≥${r.min} | ${r.pass ? '✅' : '❌'} |`,
  );
  return [
    '# Contrast report',
    '',
    'Generated — WCAG 2 relative-luminance contrast.',
    '',
    '| theme | pair | ratio | min | |',
    '|---|---|---|---|---|',
    ...rows,
    '',
  ].join('\n');
}
